### ISSUE TITLE
Make it possible to activate / deactivate measurement on user request

### ISSUE THREAD

**Issue by pkolaczk** [mfleming/performance-tools#2]
Imagine an application that requires a long startup and shutdown. 
I would like to deliberately skip measuring the startup and shutdown. 
I'd like to enable measurement only when I'm benchmarking my app, when it is fully loaded.

Ideas: 
- make it possible to attach to an existing application given by PID (not sure if at all possible though)
- open a named pipe or network channel and listen to start/stop commands sent through it - this could allow even more interesting use-cases where the benchmarking app could enable/disable measurement by itself

**Comment by mfleming** [comment]
These are all really useful scenarios, but I don't think schedtime is the right tool for them since it's designed to work just like time(1), e.g. you start a new command and it runs until it exits.

So I'm working on another project that will allow you to monitor existing processes/threads. I'll update this issue when I've got something to try out.

Thanks for the feedback!
